server:
  port: 8082

kafka:
  bootstrap-servers: "localhost:9092"
  producer:
    topic:
      real-time-prices:
        nr-of-partitions: 1
      previous-settlement-price-data:
        nr-of-partitions: 1
    broadcast:
      config:
        - partition: 0
          event-logging: 1000
          topic: "previous-settlement-price-data"
        - partition: 0
          event-logging: 10000
          topic: "real-time-prices"
  consumer:
    config:
      - offset: 0
        partition: 0
        event-logging: 10000
        topic: "system-trade-data"
      - offset: 0
        partition: 0
        event-logging: 10000
        topic: "top-of-book-quote"
      - offset: 0
        partition: 0
        event-logging: 1000
        topic: "reference-data"

market-data:
  external:
    eurex:
      api-key: "e4182894-f5e1-42ae-90a7-7f04d760cd62"
      api-url: "https://api.developer.deutsche-boerse.com/accesstot7-referencedata-1-1-0/"
      contractRequestLimit: 20
    nasdaq:
      api-key: "pLW2fjt4BxuzZSqy-4pT"
      api-url: "https://data.nasdaq.com/api/v3/datasets/USTREASURY/YIELD.json"


